#ifndef SHELLCONF_H
#define SHELLCONF_H

#define SHELL_PROMPT_STR "TAOBAO> "
#define SHELL_USE_HISTORY TRUE
#define SHELL_USE_ESC_SEQ TRUE
#define SHELL_CMD_TEST_ENABLED FALSE
#define SHELL_MAX_ARGUMENTS 16
#endif
